// <auto-generated />
using System;
using Gmlu.Demo.EntityFramework.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gmlu.Demo.EntityFramework.Migrations
{
    [DbContext(typeof(StatsContext))]
    [Migration("20210318101013_MigrationEF2")]
    partial class MigrationEF2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gmlu.Demo.EntityFramework.Models.MeasurePoint", b =>
                {
                    b.Property<Guid>("MeasurePointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MeasurePointId");

                    b.ToTable("MeasurePoint");
                });

            modelBuilder.Entity("Gmlu.Demo.EntityFramework.Models.Raspberry", b =>
                {
                    b.Property<Guid>("RaspberryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(130)")
                        .HasMaxLength(130);

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(130)")
                        .HasMaxLength(130);

                    b.HasKey("RaspberryId");

                    b.ToTable("Raspberrys");
                });
#pragma warning restore 612, 618
        }
    }
}
